//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0_track100 {
            get {
                object obj = ResourceManager.GetObject("_0_track100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0_track1500 {
            get {
                object obj = ResourceManager.GetObject("_0_track1500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0_track200 {
            get {
                object obj = ResourceManager.GetObject("_0_track200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0_track400 {
            get {
                object obj = ResourceManager.GetObject("_0_track400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0_track800 {
            get {
                object obj = ResourceManager.GetObject("_0_track800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1_hurdle {
            get {
                object obj = ResourceManager.GetObject("_1_hurdle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1_track_relay4x100 {
            get {
                object obj = ResourceManager.GetObject("_1_track_relay4x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1_track_relay4x400 {
            get {
                object obj = ResourceManager.GetObject("_1_track_relay4x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2_0_highjump {
            get {
                object obj = ResourceManager.GetObject("_2_0_highjump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2_1_polevault {
            get {
                object obj = ResourceManager.GetObject("_2_1_polevault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2_2_longjump {
            get {
                object obj = ResourceManager.GetObject("_2_2_longjump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2_3_triplejump {
            get {
                object obj = ResourceManager.GetObject("_2_3_triplejump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3_0_shortput {
            get {
                object obj = ResourceManager.GetObject("_3_0_shortput", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3_1_discus {
            get {
                object obj = ResourceManager.GetObject("_3_1_discus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3_2_javelin {
            get {
                object obj = ResourceManager.GetObject("_3_2_javelin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blue {
            get {
                object obj = ResourceManager.GetObject("blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blue_dot {
            get {
                object obj = ResourceManager.GetObject("blue_dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blue_dot_1 {
            get {
                object obj = ResourceManager.GetObject("blue_dot_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blue_dot_2 {
            get {
                object obj = ResourceManager.GetObject("blue_dot_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blue_dot_3 {
            get {
                object obj = ResourceManager.GetObject("blue_dot_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blue_dot_4 {
            get {
                object obj = ResourceManager.GetObject("blue_dot_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blue_dot_5 {
            get {
                object obj = ResourceManager.GetObject("blue_dot_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blue_dot_6 {
            get {
                object obj = ResourceManager.GetObject("blue_dot_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blue_dot_7 {
            get {
                object obj = ResourceManager.GetObject("blue_dot_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blue_dot_8 {
            get {
                object obj = ResourceManager.GetObject("blue_dot_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap button1 {
            get {
                object obj = ResourceManager.GetObject("button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap confirm {
            get {
                object obj = ResourceManager.GetObject("confirm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cross_white {
            get {
                object obj = ResourceManager.GetObject("cross_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .edk-project.
        /// </summary>
        public static string extProject {
            get {
                return ResourceManager.GetString("extProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap field {
            get {
                object obj = ResourceManager.GetObject("field", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Workbook (*.xlsx)|*.xlsx.
        /// </summary>
        public static string filterExcelFile {
            get {
                return ResourceManager.GetString("filterExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG File|*.jpg;*.jpeg|PNG (Portable Network Graphics)|*.png|Bitmap Image|*.bmp|GIF (Graphics Interchange Format)|*.gif|TIFF (Tagged Image File Format)|*.tiff.
        /// </summary>
        public static string filterExtImagesAll {
            get {
                return ResourceManager.GetString("filterExtImagesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Holder Records Excel File.
        /// </summary>
        public static string filterHolderRecordsExcelFile1 {
            get {
                return ResourceManager.GetString("filterHolderRecordsExcelFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        public static string filterImageFiles {
            get {
                return ResourceManager.GetString("filterImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Files.
        /// </summary>
        public static string filterProjectFiles {
            get {
                return ResourceManager.GetString("filterProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Information Excel File (*.csv;*.xls;*.xlsx)|*.csv;*.xls;*.xlsx.
        /// </summary>
        public static string filterStudentInfoExcelFile {
            get {
                return ResourceManager.GetString("filterStudentInfoExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap formUI {
            get {
                object obj = ResourceManager.GetObject("formUI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap formUI_Launch {
            get {
                object obj = ResourceManager.GetObject("formUI_Launch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap full_public {
            get {
                object obj = ResourceManager.GetObject("full_public", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap green {
            get {
                object obj = ResourceManager.GetObject("green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap highjump {
            get {
                object obj = ResourceManager.GetObject("highjump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon1 {
            get {
                object obj = ResourceManager.GetObject("icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap import_file {
            get {
                object obj = ResourceManager.GetObject("import_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap independent {
            get {
                object obj = ResourceManager.GetObject("independent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the data below. Answer some questions to finish importation..
        /// </summary>
        public static string instrDescription1 {
            get {
                return ResourceManager.GetString("instrDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop file here to reload..
        /// </summary>
        public static string instrDropFile1 {
            get {
                return ResourceManager.GetString("instrDropFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the holder&apos;s name.
        /// </summary>
        public static string instrHdEnterHolderName {
            get {
                return ResourceManager.GetString("instrHdEnterHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the result.
        /// </summary>
        public static string instrHdEnterResult {
            get {
                return ResourceManager.GetString("instrHdEnterResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select group.
        /// </summary>
        public static string instrHdSelectGroup {
            get {
                return ResourceManager.GetString("instrHdSelectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap intro {
            get {
                object obj = ResourceManager.GetObject("intro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap menu_btn_events_set {
            get {
                object obj = ResourceManager.GetObject("menu_btn_events_set", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap menu_btn_holder {
            get {
                object obj = ResourceManager.GetObject("menu_btn_holder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap menu_btn_house_set {
            get {
                object obj = ResourceManager.GetObject("menu_btn_house_set", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap menu_btn_schedule {
            get {
                object obj = ResourceManager.GetObject("menu_btn_schedule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap menu_btn_stu_info {
            get {
                object obj = ResourceManager.GetObject("menu_btn_stu_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MF {
            get {
                object obj = ResourceManager.GetObject("MF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} event(s) do not open any group for application. Do you want to remove them?.
        /// </summary>
        public static string msgEventGroup1 {
            get {
                return ResourceManager.GetString("msgEventGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following events do not have groups opened for applications..
        /// </summary>
        public static string msgEventGroup2 {
            get {
                return ResourceManager.GetString("msgEventGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap red {
            get {
                object obj = ResourceManager.GetObject("red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap red_dot {
            get {
                object obj = ResourceManager.GetObject("red_dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap red_dot_1 {
            get {
                object obj = ResourceManager.GetObject("red_dot_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap red_dot_2 {
            get {
                object obj = ResourceManager.GetObject("red_dot_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap red_dot_3 {
            get {
                object obj = ResourceManager.GetObject("red_dot_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap red_dot_4 {
            get {
                object obj = ResourceManager.GetObject("red_dot_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap red_dot_5 {
            get {
                object obj = ResourceManager.GetObject("red_dot_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap red_dot_6 {
            get {
                object obj = ResourceManager.GetObject("red_dot_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap red_dot_7 {
            get {
                object obj = ResourceManager.GetObject("red_dot_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap red_dot_8 {
            get {
                object obj = ResourceManager.GetObject("red_dot_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap reset {
            get {
                object obj = ResourceManager.GetObject("reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Student Info
        ///Excel File.
        /// </summary>
        public static string stateLoadStudentInfoExcelFile {
            get {
                return ResourceManager.GetString("stateLoadStudentInfoExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Custom Relay.
        /// </summary>
        public static string strAddCustomRelay {
            get {
                return ResourceManager.GetString("strAddCustomRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Events.
        /// </summary>
        public static string strAllEvents {
            get {
                return ResourceManager.GetString("strAllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemble.
        /// </summary>
        public static string strAssemble {
            get {
                return ResourceManager.GetString("strAssemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string strClass {
            get {
                return ResourceManager.GetString("strClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Number.
        /// </summary>
        public static string strClassNumber {
            get {
                return ResourceManager.GetString("strClassNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Application.
        /// </summary>
        public static string strCloseApplication {
            get {
                return ResourceManager.GetString("strCloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Ceremony.
        /// </summary>
        public static string strClosingCeremony {
            get {
                return ResourceManager.GetString("strClosingCeremony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string strColor {
            get {
                return ResourceManager.GetString("strColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string strColumn {
            get {
                return ResourceManager.GetString("strColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition.
        /// </summary>
        public static string strCompetition {
            get {
                return ResourceManager.GetString("strCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction.
        /// </summary>
        public static string strDeduction {
            get {
                return ResourceManager.GetString("strDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string strDismiss {
            get {
                return ResourceManager.GetString("strDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string strDOB {
            get {
                return ResourceManager.GetString("strDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string strEvent {
            get {
                return ResourceManager.GetString("strEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event ID.
        /// </summary>
        public static string strEventID {
            get {
                return ResourceManager.GetString("strEventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        public static string strEventName {
            get {
                return ResourceManager.GetString("strEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Settings.
        /// </summary>
        public static string strEventSettings {
            get {
                return ResourceManager.GetString("strEventSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FA.
        /// </summary>
        public static string strFA {
            get {
                return ResourceManager.GetString("strFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FB.
        /// </summary>
        public static string strFB {
            get {
                return ResourceManager.GetString("strFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC.
        /// </summary>
        public static string strFC {
            get {
                return ResourceManager.GetString("strFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FD.
        /// </summary>
        public static string strFD {
            get {
                return ResourceManager.GetString("strFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female Public.
        /// </summary>
        public static string strFGrpPub {
            get {
                return ResourceManager.GetString("strFGrpPub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Events.
        /// </summary>
        public static string strFieldEvents {
            get {
                return ResourceManager.GetString("strFieldEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string strFinal {
            get {
                return ResourceManager.GetString("strFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First row is heading.
        /// </summary>
        public static string strFirstRowIsHeading {
            get {
                return ResourceManager.GetString("strFirstRowIsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string strFullGrpPub {
            get {
                return ResourceManager.GetString("strFullGrpPub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string strGender {
            get {
                return ResourceManager.GetString("strGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string strGroup {
            get {
                return ResourceManager.GetString("strGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder Name.
        /// </summary>
        public static string strHolderName {
            get {
                return ResourceManager.GetString("strHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string strHouse {
            get {
                return ResourceManager.GetString("strHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Name.
        /// </summary>
        public static string strHouseName {
            get {
                return ResourceManager.GetString("strHouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Settings.
        /// </summary>
        public static string strHouseSettings {
            get {
                return ResourceManager.GetString("strHouseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint events.
        /// </summary>
        public static string strJointEvents {
            get {
                return ResourceManager.GetString("strJointEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane.
        /// </summary>
        public static string strLane {
            get {
                return ResourceManager.GetString("strLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string strLoading {
            get {
                return ResourceManager.GetString("strLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch Time.
        /// </summary>
        public static string strLunchTime {
            get {
                return ResourceManager.GetString("strLunchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA.
        /// </summary>
        public static string strMA {
            get {
                return ResourceManager.GetString("strMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string strMB {
            get {
                return ResourceManager.GetString("strMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        public static string strMC {
            get {
                return ResourceManager.GetString("strMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD.
        /// </summary>
        public static string strMD {
            get {
                return ResourceManager.GetString("strMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male Public.
        /// </summary>
        public static string strMGrpPub {
            get {
                return ResourceManager.GetString("strMGrpPub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed Group.
        /// </summary>
        public static string strMixGroup {
            get {
                return ResourceManager.GetString("strMixGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string strNext {
            get {
                return ResourceManager.GetString("strNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Openning.
        /// </summary>
        public static string strNotOpenning {
            get {
                return ResourceManager.GetString("strNotOpenning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Application.
        /// </summary>
        public static string strOpenApplication {
            get {
                return ResourceManager.GetString("strOpenApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Events.
        /// </summary>
        public static string strOpenEvent {
            get {
                return ResourceManager.GetString("strOpenEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Groups.
        /// </summary>
        public static string strOpenGroups {
            get {
                return ResourceManager.GetString("strOpenGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openning Ceremony.
        /// </summary>
        public static string strOpenningCeremony {
            get {
                return ResourceManager.GetString("strOpenningCeremony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation.
        /// </summary>
        public static string strParticipation {
            get {
                return ResourceManager.GetString("strParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation.
        /// </summary>
        public static string strParticipationScore {
            get {
                return ResourceManager.GetString("strParticipationScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string strPrevious {
            get {
                return ResourceManager.GetString("strPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string strPrinter {
            get {
                return ResourceManager.GetString("strPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Student Application Form.
        /// </summary>
        public static string strPrintStudentApplicationForm {
            get {
                return ResourceManager.GetString("strPrintStudentApplicationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string strRank {
            get {
                return ResourceManager.GetString("strRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank Scores.
        /// </summary>
        public static string strRankScore {
            get {
                return ResourceManager.GetString("strRankScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Printer List.
        /// </summary>
        public static string strRefreshPrinterList {
            get {
                return ResourceManager.GetString("strRefreshPrinterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rematch.
        /// </summary>
        public static string strRematch {
            get {
                return ResourceManager.GetString("strRematch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string strRemove {
            get {
                return ResourceManager.GetString("strRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        public static string strResetAll {
            get {
                return ResourceManager.GetString("strResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string strResult {
            get {
                return ResourceManager.GetString("strResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string strRevert {
            get {
                return ResourceManager.GetString("strRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Detailed Information.
        /// </summary>
        public static string strStudentDetailedInformation {
            get {
                return ResourceManager.GetString("strStudentDetailedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        public static string strStudentID {
            get {
                return ResourceManager.GetString("strStudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Information.
        /// </summary>
        public static string strStudentInformation {
            get {
                return ResourceManager.GetString("strStudentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studnet Name.
        /// </summary>
        public static string strStudentName {
            get {
                return ResourceManager.GetString("strStudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string strSuccess {
            get {
                return ResourceManager.GetString("strSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swim Gala.
        /// </summary>
        public static string strSwimGala {
            get {
                return ResourceManager.GetString("strSwimGala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string strSymbol {
            get {
                return ResourceManager.GetString("strSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string strTotalScore {
            get {
                return ResourceManager.GetString("strTotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Events.
        /// </summary>
        public static string strTrackEvents {
            get {
                return ResourceManager.GetString("strTrackEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string strUnknown {
            get {
                return ResourceManager.GetString("strUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string strWarning {
            get {
                return ResourceManager.GetString("strWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        public static string strWinner {
            get {
                return ResourceManager.GetString("strWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string strYear {
            get {
                return ResourceManager.GetString("strYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stu_drop {
            get {
                object obj = ResourceManager.GetObject("stu_drop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap swim {
            get {
                object obj = ResourceManager.GetObject("swim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap track {
            get {
                object obj = ResourceManager.GetObject("track", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap track_relay {
            get {
                object obj = ResourceManager.GetObject("track_relay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap trans {
            get {
                object obj = ResourceManager.GetObject("trans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap trash {
            get {
                object obj = ResourceManager.GetObject("trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap violet {
            get {
                object obj = ResourceManager.GetObject("violet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap xls_icon {
            get {
                object obj = ResourceManager.GetObject("xls_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap yellow {
            get {
                object obj = ResourceManager.GetObject("yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
